include:
  - board: nrf52840dk_nrf52840
    shield: corne_left nice_view_adapter nice_view
  - board: nrf52840dk_nrf52840
    shield: corne_right nice_view_adapter nice_view
  - board: nrf52840dk_nrf52840
    shield: settings_reset
